import typing

from .types import Wagon, Era, Payment, Token, Material

WAGONS = [
    Wagon(
        name="Pullman",
        era=Era.EARLY_STEAM,
        requires_depot_extension=False,
        cargo=Material.PASSENGERS,
        capacity=8,
        unloaded=15,
        loaded=16,
        length=0.56,
        cost=[Payment(10, Token.MONEY)],
    ),
    Wagon(
        name="Coach Car",
        era=Era.EARLY_STEAM,
        requires_depot_extension=False,
        cargo=Material.PASSENGERS,
        capacity=15,
        unloaded=20,
        loaded=22,
        length=0.92,
        cost=[Payment(22, Token.MONEY)],
    ),
    Wagon(
        name="1st Class",
        era=Era.STEAM,
        requires_depot_extension=True,
        cargo=Material.PASSENGERS,
        capacity=18,
        unloaded=40,
        loaded=42,
        length=1.28,
        cost=[Payment(22, Token.TIMBER), Payment(8, Token.COAL)],
        special="Income +10%",
    ),
    Wagon(
        name="2nd Class",
        era=Era.EARLY_STEAM,
        requires_depot_extension=False,
        cargo=Material.PASSENGERS,
        capacity=25,
        unloaded=35,
        loaded=38,
        length=1.28,
        cost=[Payment(20, Token.TIMBER)],
    ),
    Wagon(
        name="Dining car",
        era=Era.STEAM,
        requires_depot_extension=True,
        cargo=Material.PASSENGERS,
        capacity=0,
        unloaded=50,
        loaded=50,
        length=1.28,
        cost=[Payment(35, Token.TIMBER), Payment(30, Token.COAL)],
        special="Income +15%",
    ),
    Wagon(
        name="SCF",
        era=Era.DIESEL,
        requires_depot_extension=False,
        cargo=Material.PASSENGERS,
        capacity=40,
        unloaded=40,
        loaded=44,
        length=1.28,
        cost=[Payment(150, Token.MONEY), Payment(35, Token.TIMBER)],
    ),
    Wagon(
        name="SCF Diner",
        era=Era.DIESEL,
        requires_depot_extension=True,
        cargo=Material.PASSENGERS,
        capacity=0,
        unloaded=50,
        loaded=50,
        length=1.36,
        cost=[Payment(300, Token.MONEY), Payment(80, Token.COAL)],
        special="Income +20%",
    ),
    Wagon(
        name="Pwg PR-14",
        era=Era.STEAM,
        requires_depot_extension=False,
        cargo=Material.MAIL,
        capacity=7,
        unloaded=22,
        loaded=29,
        length=0.48,
        cost=[Payment(30, Token.MONEY)],
    ),
    Wagon(
        name="SCF Mail",
        era=Era.DIESEL,
        requires_depot_extension=False,
        cargo=Material.MAIL,
        capacity=20,
        unloaded=40,
        loaded=42,
        length=1.36,
        cost=[Payment(120, Token.MONEY), Payment(35, Token.TIMBER)],
    ),
    Wagon(
        name="Hatch",
        era=Era.EARLY_DIESEL,
        requires_depot_extension=False,
        cargo=Material.CRUDE_OIL,
        capacity=4,
        unloaded=14,
        loaded=22,
        length=0.5,
        cost=[Payment(80, Token.MONEY)],
    ),
    Wagon(
        name="Warren",
        era=Era.EARLY_DIESEL,
        requires_depot_extension=False,
        cargo=Material.CRUDE_OIL,
        capacity=7,
        unloaded=18,
        loaded=32,
        length=0.66,
        cost=[Payment(40, Token.TIMBER)],
    ),
    Wagon(
        name="Steudinger",
        era=Era.EARLY_STEAM,
        requires_depot_extension=False,
        cargo=Material.LOGS,
        capacity=7,
        unloaded=14,
        loaded=21,
        length=0.67,
        cost=[Payment(12, Token.MONEY)],
    ),
    Wagon(
        name="Nossinger",
        era=Era.EARLY_STEAM,
        requires_depot_extension=True,
        cargo=Material.LOGS,
        capacity=11,
        unloaded=18,
        loaded=29,
        length=1.05,
        cost=[Payment(10, Token.TIMBER)],
    ),
    Wagon(
        name="Ronghoffer",
        era=Era.EARLY_STEAM,
        requires_depot_extension=False,
        cargo=Material.TIMBER,
        capacity=7,
        unloaded=15,
        loaded=29,
        length=0.75,
        cost=[Payment(20, Token.MONEY)],
    ),
    Wagon(
        name="Ronghoffer II",
        era=Era.EARLY_STEAM,
        requires_depot_extension=True,
        cargo=Material.TIMBER,
        capacity=15,
        unloaded=20,
        loaded=50,
        length=1.16,
        cost=[Payment(15, Token.IRON)],
    ),
    Wagon(
        name="Hatch II",
        era=Era.EARLY_DIESEL,
        requires_depot_extension=False,
        cargo=Material.DIESEL,
        capacity=7,
        unloaded=15,
        loaded=29,
        length=0.55,
        cost=[Payment(100, Token.MONEY), Payment(30, Token.TIMBER)],
    ),
    Wagon(
        name="Warren II",
        era=Era.EARLY_DIESEL,
        requires_depot_extension=False,
        cargo=Material.DIESEL,
        capacity=12,
        unloaded=16,
        loaded=40,
        length=0.61,
        cost=[Payment(20, Token.IRON)],
    ),
    Wagon(
        name="Opeln",
        era=Era.EARLY_DIESEL,
        requires_depot_extension=False,
        cargo=Material.GOODS,
        capacity=7,
        unloaded=11,
        loaded=18,
        length=0.55,
        cost=[Payment(200, Token.MONEY), Payment(50, Token.TIMBER)],
    ),
    Wagon(
        name="Hiblns",
        era=Era.EARLY_DIESEL,
        requires_depot_extension=False,
        cargo=Material.GOODS,
        capacity=12,
        unloaded=14,
        loaded=26,
        length=0.77,
        cost=[Payment(75, Token.TIMBER), Payment(30, Token.IRON)],
    ),
    Wagon(
        name="Fischer",
        era=Era.STEAM,
        requires_depot_extension=False,
        cargo=Material.IRON_ORE,
        capacity=8,
        unloaded=16,
        loaded=32,
        length=0.46,
        cost=[Payment(30, Token.MONEY)],
    ),
    Wagon(
        name="Linz II",
        era=Era.STEAM,
        requires_depot_extension=False,
        cargo=Material.IRON_ORE,
        capacity=12,
        unloaded=18,
        loaded=42,
        length=0.55,
        cost=[Payment(20, Token.TIMBER)],
    ),
    Wagon(
        name="Faccs II",
        era=Era.STEAM,
        requires_depot_extension=True,
        cargo=Material.IRON_ORE,
        capacity=16,
        unloaded=20,
        loaded=52,
        length=0.68,
        cost=[Payment(60, Token.MONEY), Payment(10, Token.IRON)],
    ),
    Wagon(
        name="Talbot",
        era=Era.EARLY_STEAM,
        requires_depot_extension=False,
        cargo=Material.COAL,
        capacity=6,
        unloaded=13,
        loaded=25,
        length=0.39,
        cost=[Payment(15, Token.MONEY)],
    ),
    Wagon(
        name="Linz",
        era=Era.EARLY_STEAM,
        requires_depot_extension=False,
        cargo=Material.COAL,
        capacity=9,
        unloaded=18,
        loaded=36,
        length=0.55,
        cost=[Payment(16, Token.TIMBER)],
    ),
    Wagon(
        name="Faccs",
        era=Era.EARLY_STEAM,
        requires_depot_extension=True,
        cargo=Material.COAL,
        capacity=15,
        unloaded=16,
        loaded=46,
        length=0.51,
        cost=[Payment(9, Token.IRON)],
    ),
    Wagon(
        name="Ignax Schustel",
        era=Era.STEAM,
        requires_depot_extension=False,
        cargo=Material.IRON,
        capacity=4,
        unloaded=12,
        loaded=32,
        length=0.58,
        cost=[Payment(55, Token.MONEY)],
    ),
    Wagon(
        name="Schustel II",
        era=Era.STEAM,
        requires_depot_extension=False,
        cargo=Material.IRON,
        capacity=6,
        unloaded=15,
        loaded=45,
        length=0.79,
        cost=[Payment(22, Token.TIMBER)],
    ),
    Wagon(
        name="Schustel III",
        era=Era.STEAM,
        requires_depot_extension=False,
        cargo=Material.IRON,
        capacity=8,
        unloaded=18,
        loaded=58,
        length=0.78,
        cost=[Payment(15, Token.IRON)],
    ),
    Wagon(
        name="Muller",
        era=Era.DIESEL,
        requires_depot_extension=False,
        cargo=Material.STEEL,
        capacity=3,
        unloaded=12,
        loaded=27,
        length=0.62,
        cost=[Payment(110, Token.MONEY)],
    ),
    Wagon(
        name="Muller II",
        era=Era.DIESEL,
        requires_depot_extension=False,
        cargo=Material.STEEL,
        capacity=4,
        unloaded=14,
        loaded=34,
        length=0.81,
        cost=[Payment(50, Token.TIMBER)],
    ),
    Wagon(
        name="Muller III",
        era=Era.DIESEL,
        requires_depot_extension=False,
        cargo=Material.STEEL,
        capacity=5,
        unloaded=16,
        loaded=41,
        length=0.97,
        cost=[Payment(26, Token.IRON)],
    ),
    Wagon(
        name="Cackle",
        era=Era.DIESEL,
        requires_depot_extension=False,
        cargo=Material.SAND,
        capacity=5,
        unloaded=8,
        loaded=18,
        length=0.45,
        cost=[Payment(80, Token.MONEY)],
    ),
    Wagon(
        name="Cackle II",
        era=Era.DIESEL,
        requires_depot_extension=False,
        cargo=Material.SAND,
        capacity=7,
        unloaded=11,
        loaded=25,
        length=0.58,
        cost=[Payment(35, Token.TIMBER)],
    ),
    Wagon(
        name="Snowflake Food",
        era=Era.EARLY_ELECTRIC,
        requires_depot_extension=False,
        cargo=Material.FOOD,
        capacity=10,
        unloaded=25,
        loaded=35,
        length=0.78,
        cost=[Payment(300, Token.MONEY), Payment(75, Token.TIMBER)],
    ),
    Wagon(
        name="Snowflake Food Ex",
        era=Era.EARLY_ELECTRIC,
        requires_depot_extension=False,
        cargo=Material.FOOD,
        capacity=18,
        unloaded=35,
        loaded=53,
        length=1.00,
        cost=[Payment(100, Token.TIMBER), Payment(45, Token.IRON)],
    ),
]
